/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello;

public class Hello {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Hello().getGreeting());
    }
}
