/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello;

import org.junit.Test;
import static org.junit.Assert.*;

public class HelloTest {
    @Test public void appHasAGreeting() {
        Hello classUnderTest = new Hello();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
